apiVersion: v2
name: ark-cluster
<<<<<<< HEAD
version: 0.0.6
=======
version: 0.0.7
>>>>>>> gh-pages
description: A Helm chart for an Ark - Survival Evolved cluster
type: application
appVersion: latest
home: https://store.steampowered.com/app/346110/ARK_Survival_Evolved/
keyworks:
  - game
  - server
  - steam
  - ark
sources:
  - https://github.com/DrPsychick/ark-server-charts
maintainers:
  - name: DrPsychick
    email: drpsychick@drsick.net
    url: https://github.com/DrPsychick
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/thmhoag/arkserver
    - name: Image DockerHub
      url: https://hub.docker.com/r/drpsychick/arkcluster
