name: Helm Charts
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: cr-config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
